---
- name: Deploy Prometheus and Grafana
  hosts: localhost
  connection: local
  vars:
    kubeconfig: "{{ lookup('env', 'HOME') }}/.kube/config"
    namespace: monitoring

  tasks:
    - name: Create monitoring namespace
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig }}"
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ namespace }}"

    - name: Deploy Prometheus
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig }}"
        state: present
        definition:
          - apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: prometheus
              namespace: "{{ namespace }}"
            spec:
              replicas: 1
              selector:
                matchLabels:
                  app: prometheus
              template:
                metadata:
                  labels:
                    app: prometheus
                spec:
                  containers:
                    - name: prometheus
                      image: prom/prometheus:latest
                      ports:
                        - containerPort: 9090
                      volumeMounts:
                        - name: config-volume
                          mountPath: /etc/prometheus
                  volumes:
                    - name: config-volume
                      configMap:
                        name: prometheus-config

          - apiVersion: v1
            kind: Service
            metadata:
              name: prometheus-service
              namespace: "{{ namespace }}"
            spec:
              selector:
                app: prometheus
              ports:
                - port: 9090
                  targetPort: 9090
              type: NodePort

    - name: Create Prometheus ConfigMap
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig }}"
        state: present
        definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: prometheus-config
            namespace: "{{ namespace }}"
          data:
            prometheus.yml: |
              global:
                scrape_interval: 15s
              scrape_configs:
                - job_name: 'devops-app'
                  static_configs:
                    - targets: ['devops-app-service.devops-project.svc.cluster.local:80']
                  metrics_path: /metrics
                  scrape_interval: 5s

    - name: Deploy Grafana
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig }}"
        state: present
        definition:
          - apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: grafana
              namespace: "{{ namespace }}"
            spec:
              replicas: 1
              selector:
                matchLabels:
                  app: grafana
              template:
                metadata:
                  labels:
                    app: grafana
                spec:
                  containers:
                    - name: grafana
                      image: grafana/grafana:latest
                      ports:
                        - containerPort: 3000
                      env:
                        - name: GF_SECURITY_ADMIN_PASSWORD
                          value: "admin"
          - apiVersion: v1
            kind: Service
            metadata:
              name: grafana-service
              namespace: "{{ namespace }}"
            spec:
              selector:
                app: grafana
              ports:
                - port: 3000
                  targetPort: 3000
              type: NodePort
