# .github/workflows/ci-cd.yml
name: Build and Deploy to OpenShift

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # This runs in a GitHub-hosted VM

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Local Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.REGISTRY_URL }} # We will set this secret
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.REGISTRY_URL }}https://devops-app:${{ github.sha }}
        # Build for the linux/amd64 platform to match the cluster
        platforms: linux/amd64

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform

    - name: Terraform Apply
      run: terraform apply -auto-approve -var="image_tag=${{ secrets.REGISTRY_URL }}/devops-app:${{ github.sha }}"
      working-directory: ./terraform
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
