name: Build and Package Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        tags: devops-app:${{ github.sha }}
        platforms: linux/amd64
        load: true # This loads the image into the runner's Docker daemon
        push: false # We are not pushing to a registry

    - name: Save Docker Image to File
      run: |
        mkdir -p image-artifact
        docker save devops-app:${{ github.sha }} -o image-artifact/devops-app.tar

    - name: Upload Image Artifact
      uses: actions/upload-artifact@v3
      with:
        name: devops-app-image
        path: image-artifact/
        retention-days: 1
