name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.MINIKUBE_REGISTRY_URL }}/devops-app:${{ github.sha }}
        platforms: linux/amd64

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform

# ... (previous steps) ...

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Prepare kubeconfig
      run: |
        mkdir -p /home/runner/.kube
        echo "${{ secrets.KUBE_CONFIG }}" > /home/runner/.kube/config

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform

    - name: Terraform Apply
      run: terraform apply -auto-approve -var="image_tag=${{ github.sha }}" -var="minikube_registry_url=${{ secrets.MINIKUBE_REGISTRY_URL }}"
      working-directory: ./terraform
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

# ... (rest of the file) ...

    - name: Terraform Apply
      run: terraform apply -auto-approve -var="image_tag=${{ github.sha }}" -var="minikube_registry_url=${{ secrets.MINIKUBE_REGISTRY_URL }}"
      working-directory: ./terraform
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
